[project]
name = "transparent-donations"
description = "A simple, transparent donation contract on Stacks."
authors = ["Gemini Code Assist"]
telemetry = true
requirements = []
[contracts.transparent-donations]
path = "contracts/transparent-donations.clar"
depends_on = []

[repl]
clarity_version = 2
[repl.analysis]
passes = ["check_checker"]

[runners.test]
# The path to the file that contains your test suites.
# The path is relative to the root of your project.
main = "tests/transparent-donations_test.ts"

[accounts]
deployer = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
wallet_1 = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5"
wallet_2 = "ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG"

# The beneficiary account for the donations
beneficiary = "ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG"
